###Person 

###Index
GET http://localhost:3000/people/all

###Show
GET http://localhost:3000/people/1

###Edit need to fix
PATCH http://localhost:3000/people/1
Content-Type: application/json

{
  "first_name": " ",
  "last_name": " ",
  "email": " ",
  "phone": ,
  "title": ,
  "github": " ",
  "linkedin": "",
  "location": "Dallas"
}

###          SKILL
### Index
GET http://localhost:3000/skill/all

### CREATE
POST http://localhost:3000/skill/add
Content-Type: application/json

{
  "name": "Github"
}