###                PERSON 

###Index
GET http://localhost:3000/people/all

###Show
GET http://localhost:3000/people/1

###Edit need to fix
PATCH http://localhost:3000/people/1
Content-Type: application/json

{
  "first_name": "Jonathan",
  "last_name": "Hoarau",
  "email": "test@test.com",
  "phone": 2424242424242,
  "title": "Software Engineer",
  "github": "github.com/jonhoa",
  "linkedin": "linkedin",
  "location": "Dallas"
}

###          SKILL
### Index
GET http://localhost:3000/skill/all

### CREATE
POST http://localhost:3000/skill/add
Content-Type: application/json

{
  "name": "Github"
}


###        EDUCATION
###Index
GET http://localhost:3000/education/all